# fly.toml app configuration file generated for nature-base on 2023-09-26T11:44:46+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nature-base"
primary_region = "lhr"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
